### ISSUE TITLE
let-flow fails to recognize dependency graph in specific usage of `case`

### ISSUE THREAD

**Issue by aengelberg** [ztellman/manifold#104]
```
(d/let-flow [x 1
             y (case :x
                 :x x
                 {})]
  y)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: x in this context
```

Oddly, in my experiments, swapping out `{}` with a non-map value makes the call succeed.

Clojure version: 1.8.0
Manifold version: 0.1.5

**Comment by ztellman** [comment]
This is probably a bug in Riddley, I've already had a few issues with case
macroexpansion being really fiddly. I'll take a look, thanks for the
report.

**Comment by ztellman** [comment]
This was an issue in how I was parsing the `case*` special form: I assumed there was only one map in the form, which wasn't true since you defined a default value which was also a map.  You can target `[riddley "0.1.14"]` to fix this, and I'll cut a new release targeting this version in the near future.
