### ISSUE TITLE
what dose stream/splice mean

### ISSUE THREAD

**Issue by 87260280** [ztellman/manifold#113]
hi, thanks for you commited such a great framework for  building tcp stream processer!
but I was confused by the splice used in aleth/tcp example 

```
(defn wrap-duplex-stream
  [protocol s]
  (let [out (s/stream)]
    (s/connect
      (s/map #(io/encode protocol %) out)
      s)
    (s/splice
      out
      (io/decode-stream s protocol))))


(defn fast-echo-handler
  [f]
  (fn [s info]
    (s/connect
      (s/map f s)
      s)))

(fast-echo-handler inc)
```

so，how could fast-echo-handler decorate a inc function to the out stream and take effect on the stream retuend by splice function？ thanks！

**Comment by ztellman** [comment]
Hi, the `splice` function takes a sink and a source and turns them into a duplex stream, where messages that are `put!` to the stream aren't something that you can `take!` from that same stream.  This is how TCP sockets are modeled: you read by taking from the socket, and write by putting to the same socket.  

Since we want to wrap the socket in something that encodes and decodes per the protocol, we need to create a shim which produces decoded messages, and encodes the messages before they're forwarded to the raw socket.  That's what `wrap-duplex-stream` is doing.

Does that make sense?

**Comment by 87260280** [comment]
I've got it !  a little confused! that means wrap the two stream and splice them to a socket like handle! thanks!
