### ISSUE TITLE
Any chance of ClojureScript port?

### ISSUE THREAD

**Issue by ul** [ztellman/manifold#2]
I suppose there are problems with javascript one-threaded execution in browser, but you always have brilliant solutions ;-)

**Comment by rhacker** [comment]
me too, I would love to see a port on Clojurescript :+1:

**Comment by DomKM** [comment]
I'd love to see a ClojureScript port as well. Unfortunately, blocking `deref`s preclude a direct ClojureScript port. ClojureScript compatibility would require fundamentally breaking API changes to remove all blocking. @ztellman, is this something you'd be open to?

**Comment by ztellman** [comment]
Can we just make `deref` throw whatever the JS equivalent of an `UnsupportedOperationException` is?

**Comment by DomKM** [comment]
As you said, many things would not survive the transition. I don't actually see why `future` wouldn't transfer (assuming `manifold.deferred` mostly transferred) but things like `stream->seq` certainly wouldn't because they assume operations can block.

I suppose you could just not support `deref` in ClojureScript and have APIs that differ in that regard. I was thinking something like core.async's `<!` (non-blocking) and `<!!` (blocking) would be more pleasant and clear.

P.S. JS uses `TypeError` for undefined method invocations, which is probably what this would fall under. There are very few native JS error types and they don't make much sense. :disappointed:  We could throw a plain string `"UnsupportedOperationException"`. :wink:

**Comment by ztellman** [comment]
Since `future` implies that the work will be done on another thread, I don't see how that would work unless we're implementing some sort of web workers thing.

The "just replace `<!!` with `<!`" thing that core.async does is only possible via the `go` macro, which Manifold doesn't have.  Frankly, I'm okay with just omitting anything that won't work in JS-land via some sort of reader conditional, but I don't know what the standard approach is for this kind of thing.

**Comment by DomKM** [comment]
`(future & body)` could synchronously return a Deferred that would be fulfilled by the eventual result of `body`. Same as in Clojure but without a new thread. Without that, I don't see a succinct facility in Manifold for "do this chunk of work asynchronously and give me a handle to its eventual result."  In core.async, that would be `(go work-to-do)` which would return a channel onto which the result of `work-to-do` would be put.

In terms of converting to CLJS, omitting incompatible functionality seems fair. Unfortunately, this means that ClojureScript lacks `promise`, `future`, and anything else that blocks, which is why core.async is great from a code unification perspective. Is `let-flow` an adequate replacement for `go`?

**Comment by ztellman** [comment]
I think `future` would either be replaced by `loop` or `let-flow`, if it's an actual async workflow.  If it's not, `go` just wraps whatever the synchronous return value is with a channel, so you could just use `chain`, I guess.

`let-flow` is more capable than `go` w.r.t. concurrency, but less capable w.r.t. handling arbitrary code structure.  Frankly, Manifold has a much weaker pitch in JS-land, since there are fewer incompatible async representations (though I guess promises are going to be standard in ES6?).  I don't have a lot invested in having a JS port, if core.async is good enough.

**Comment by metasoarous** [comment]
There is less pressure in JS-land, but it would still be nice to have some common subset of Manifold as a clj/cljs agnostic language for working with asynchronous workflows/streams. This would seem to be in line with Manifold's goal of being a translation layer.

I'd personally love to be using Manifold and Aleph to work with Datsync, but it's less of a sell to me if I can't be using it browser side.

**Comment by ztellman** [comment]
Manifold uses a number of JVM-specific tools, including weak references, to do what it does.  I understand there are equivalents in the JS ecosystem, but the additional complexity of supporting both versions honestly just isn't worth it to me.  I'd welcome a parallel CLJS library that steals liberally from Manifold, but I don't think I'm going to try to handle both in this library.

**Comment by metasoarous** [comment]
Totally respect that position. And that should be easy enough to work with given cljc.

A possible middle way: If Manifold is built on protocols, it might be possible to hide all of the JVM specific tools as implementation details, leaving room for some cljs developer to go an implement those protocols in cljs using whatever equivalent exist in JS. The advantage would be that any code/functions written on top of those protocol functions should be cljc compatible (as long as our protocol abstractions aren't too leaky), potentially reducing code overlap and creating a tighter coupling between the two implementations, without requiring you to actually write the cljs implementations. Of course, the downside is that it's still more work for you getting those protocols right, so I understand if that isn't worth it to you either.

Either way, thanks for making awesome things and giving great talks :-)

**Comment by ztellman** [comment]
I'm not saying it will never happen, but I already have too much on my plate right now.  Feel free to bug me about it in a year or so.

**Comment by metasoarous** [comment]
Sure thing. Thanks for considering it.


On Sun, Jul 3, 2016, 2:17 PM Zach Tellman <notifications@github.com> wrote:

> I'm not saying it will never happen, but I already have too much on my
> plate right now. Feel free to bug me about it in a year or so.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ztellman/manifold/issues/2#issuecomment-230175937>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFZ7EhZPZdd25XMKZhaWl_i-Nc8T6HYks5qSCb2gaJpZM4CM0lB>
> .
>
-- 

Chris

Sent via mobile

**Comment by dm3** [comment]
You might like to know that a Clojurescript port of Manifold now exists - https://github.com/dm3/manifold-cljs
