### ISSUE TITLE
Fake clocks for deterministic testing

### ISSUE THREAD

**Issue by lvh** [ztellman/manifold#57]
We have some code that wants to do something periodically. The original version used core.async + timeout, which, while a lot of code, allowed re-use of some code I wrote [in icecap](https://github.com/lvh/icecap/blob/4c45f92d9db248f173728843f3f1320864c852b8/test/icecap/handlers/delay_test.clj#L9-L42) that gives me a fake clock, a la [`twisted.internet.task.Clock`](https://twistedmatrix.com/documents/current/api/twisted.internet.task.Clock.html). I'll take it as given that having a deterministic clock like this is desirable; I'd be happy to elaborate if that's a point of contention :smile: 

That piece of core.async code predictably became a lot smaller when using manifold instead, but of course manifold happily ignored my pleas to rebind `timeout`. I'm trying to figure out what the best way to do this in Manifold would be. I think the answer is to implement a fake scheduler. https://github.com/ztellman/manifold/blob/master/src/manifold/time.clj#L175 constrains this to be a `ScheduledThreadPoolExecutor`, which is fine. Alas, the [`let` binding](https://github.com/ztellman/manifold/blob/master/src/manifold/time.clj#L130-L138) means I don't know how to override that. I'm not entirely sure why that doesn't use `(manifold.executor/executor)`. I _think_ that's a thread local and not a dynamic variable because of performance, but I'm not sure.

Thanks in advance!

cc @derwolfe

**Comment by ztellman** [comment]
Yes, this is something which would clearly be useful.  There are two ways we can handle this: 

* make the clock an explicit parameter on every timeout-related operation
* allow some sort of `*clock*` var to be dynamically rebound, and have that be implicitly used by the underlying `manifold.time` methods.

I'm leaning towards the latter, since it doesn't add a bunch of noise to the (many) methods which call into `manifold.time` under the covers.  Any thoughts on this?

**Comment by lvh** [comment]
Don't care, latter seems fine. Why separate clock from thread-local executor at all?

**Comment by ztellman** [comment]
I'm not sure I understand the question.  I can't use `executor` because it's not a scheduled-executor, which has more complicated stuff going on under the covers.  I may create a scheduled executor implementation in Dirigiste, but it's not an immediate need.

In either case, in this case I don't need a full-fledged `ScheduledExecutor`, which means that I could (for instance) use Netty's scheduling facilities, or whatever else is convenient.  I'll take a closer look at this later tonight.

**Comment by lvh** [comment]
Oh; I see; I didn't realize that the default executor wasn't (and wouldn't be) scheduled. Gotcha. In that sense, `*clock*` is perfect. Is the global scheduler not a dynamic var because of perf?

**Comment by ztellman** [comment]
There's a tiny performance win from doing it that way, but mostly I just meant to make sure it was an internal detail (i.e. that no one would try to do what you were trying to do).  Anyway, I'l have some sort of spec together for this presently.

**Comment by ztellman** [comment]
I think the implementation I put together is pretty self-explanatory, but let me know if anything isn't clear.

**Comment by lvh** [comment]
Thanks a lot! We landed stuff that uses this and it seems to work as expected :)

**Comment by derwolfe** [comment]
Thank you! This has been a pleasure to use :-)
On Sat, Jan 9, 2016 at 13:41 lvh <notifications@github.com> wrote:

> Thanks a lot! We landed stuff that uses this and it seems to work as
> expected :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ztellman/manifold/issues/57#issuecomment-170273945>.
>
-- 
- Chris
