### ISSUE TITLE
What happens to errors in s/consume?

### ISSUE THREAD

**Issue by vspinu** [ztellman/manifold#99]
What's the correct way to handle errors in `consume`? The following returns `<<true>>` and no trace of error anywhere:

```clj
(s/consume #(throw (ex-info "error" {:val %})) (s/->source (range 10)))
```

This is probably related to #95 but I don't quite understand that issue, so opening a new one. 

Thanks.

**Comment by vspinu** [comment]
My expectation is that the above code should return the error itself (like `d/chain`  does) which I can then `d/catch`.

**Comment by dm3** [comment]
`s/consume` returns a deferred that delivers `true` when the source stream is exhausted *or an error happens*, which isn't mentioned in the docs. In your example the source stream gets closed too, because `s/consume` is its only sink. However, if you had more sinks attached, e.g.

```clojure
(def s (s/stream))
(def o (s/stream))
(s/connect s o)
(s/consume #(throw (ex-info "error" {})) s)
(s/put! s 1)
```
the source `s` wouldn't be drained after `consume` failed.

Issue #95 adds the capability to `d/catch` the errors happening in stream-processing functions, so that you could:

```clojure
(-> (s/consume ...)
      (d/catch #(println "ERROR:" %s))
```
However, it needs more work and review/blessings from @ztellman.

**Comment by vspinu** [comment]
Thanks for the explanation. Solution to #95 would be great indeed.

My confusion was coming from the fact that I didn't see any error messages.  It turned out that the errors were swallowed by CIDER's hidden server buffer. A long standing issue with nrepl/CIDER :(.
